name: acceptance
on: [pull_request]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v14.1
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: dx-oss/nix-shell-action@v11
      with:
        file: shell.nix
        script: tree-sitter test
  acceptance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v14.1
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: dx-oss/nix-shell-action@v11
      with:
        file: shell.nix
        script: tree-sitter parse --quiet --stat example/real_world/*/*.promql
